spring:
  application:
    name: shawarma-cloud
  thymeleaf:
    cache: false
  cassandra:
    keyspace-name: shawarmacloud
    schema-action: recreate
    local-datacenter: datacenter1
server:
  port: 8080