spring:
  application:
    name: shawarma_cloud
  thymeleaf:
    cache: false
  cassandra:
    keyspace-name: shawarma_cloud
    schema-action: recreate
    local-datacenter: datacenter1
server:
  port: 8080