spring:
  application:
    name: shawarma-cloud
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: "shawarmacloud"
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  h2:
    console:
      enabled: true
server:
  port: 8080