spring:
  application:
    name: shawarma_cloud
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: password
      database: shawarma_cloud
server:
  port: 8080